-- Fotografía fiel del esquema Postgres tal como existe hoy (antes de las
-- mejoras de V2 en adelante), generada contrastando el DDL real de Hibernate
-- (ddl-auto=update, pg_dump --schema-only contra un contenedor local recién
-- puesto al día) con las 14 entidades JPA — NO es una copia de schema.sql,
-- que ya estaba desalineado (longitudes, DEFAULTs y los índices reales de
-- @Table(indexes=...) que nunca reflejó).
--
-- Este script NUNCA se ejecuta contra una base de datos que ya tiene el
-- esquema (p. ej. producción en Render): spring.flyway.baseline-on-migrate
-- + baseline-version=1 hace que Flyway se autobaselice en la versión 1 sin
-- correr este SQL. Solo corre de verdad contra una Postgres nueva/vacía
-- (docker-compose local, futuros entornos), para que terminen idénticas al
-- punto de partida real antes de aplicar V2 en adelante.

CREATE EXTENSION IF NOT EXISTS postgis;

-- =============================================================================
-- Tablas
-- =============================================================================

CREATE TABLE usuario (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre character varying(255) NOT NULL,
    correo character varying(255) NOT NULL,
    password_hash character varying(200) NOT NULL,
    telefono character varying(30),
    foto_url character varying(255),
    rol character varying(20) NOT NULL,
    fecha_registro timestamp(6) without time zone NOT NULL,
    habeas_data_aceptado boolean NOT NULL,
    activo boolean NOT NULL,
    token_version integer NOT NULL,
    CONSTRAINT usuario_correo_key UNIQUE (correo),
    CONSTRAINT usuario_rol_check CHECK (((rol)::text = ANY ((ARRAY['CLIENTE'::character varying, 'TECNICO'::character varying, 'ADMINISTRADOR'::character varying, 'CONTABLE'::character varying, 'PROVEEDOR'::character varying])::text[])))
);

CREATE TABLE tecnico (
    id uuid PRIMARY KEY,
    usuario_id bigint NOT NULL,
    numero_identificacion character varying(255) NOT NULL,
    categorias_servicio character varying(4000),
    estado_operativo character varying(255),
    estado_validacion character varying(255) NOT NULL,
    motivo_rechazo_validacion character varying(500),
    certificaciones character varying(4000),
    activo boolean NOT NULL,
    latitud double precision,
    longitud double precision,
    tracking_activo boolean NOT NULL,
    ubicacion_actualizada_en timestamp(6) with time zone,
    CONSTRAINT tecnico_usuario_id_key UNIQUE (usuario_id),
    CONSTRAINT tecnico_numero_identificacion_key UNIQUE (numero_identificacion),
    CONSTRAINT tecnico_estado_operativo_check CHECK (((estado_operativo)::text = ANY ((ARRAY['DISPONIBLE'::character varying, 'OCUPADO'::character varying, 'FUERA_DE_SERVICIO'::character varying, 'BLOQUEADO_POR_LIQUIDACION'::character varying])::text[]))),
    CONSTRAINT tecnico_estado_validacion_check CHECK (((estado_validacion)::text = ANY ((ARRAY['PENDIENTE'::character varying, 'APROBADO'::character varying, 'RECHAZADO'::character varying, 'SUSPENDIDO'::character varying])::text[])))
);

CREATE TABLE documento_tecnico (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tecnico_id uuid NOT NULL,
    tipo character varying(255) NOT NULL,
    fecha_vencimiento date
);

CREATE TABLE clientes (
    id uuid PRIMARY KEY,
    usuario_id bigint NOT NULL,
    tipo character varying(10) NOT NULL,
    direccion_principal character varying(500),
    latitud double precision,
    longitud double precision,
    activo boolean NOT NULL,
    CONSTRAINT clientes_usuario_id_key UNIQUE (usuario_id),
    CONSTRAINT clientes_tipo_check CHECK (((tipo)::text = ANY ((ARRAY['B2B'::character varying, 'B2C'::character varying])::text[])))
);

CREATE TABLE token_recuperacion (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    usuario_id bigint NOT NULL,
    token_hash character varying(64) NOT NULL,
    expira_en timestamp(6) with time zone NOT NULL,
    usado boolean NOT NULL,
    creado_en timestamp(6) with time zone NOT NULL,
    CONSTRAINT token_recuperacion_token_hash_key UNIQUE (token_hash)
);

CREATE TABLE ot (
    id uuid PRIMARY KEY,
    cliente_id uuid NOT NULL,
    tecnico_id uuid,
    categoria_servicio character varying(30),
    descripcion_falla character varying(1000),
    evidencia_urls character varying(4000),
    direccion character varying(500),
    latitud double precision,
    longitud double precision,
    estado character varying(30) NOT NULL,
    radio_km double precision,
    ventana_expira_en timestamp(6) with time zone,
    creada_en timestamp(6) with time zone,
    asignada_en timestamp(6) with time zone,
    finalizada_en timestamp(6) with time zone,
    cancelada_por character varying(20),
    motivo_cancelacion character varying(30),
    tarifa_visita numeric(12,2),
    diagnostico character varying(4000),
    presupuesto character varying(4000),
    distancia_km double precision,
    tarifa_fuente character varying(20),
    auxiliares_requeridos integer DEFAULT 0 NOT NULL,
    version bigint NOT NULL,
    CONSTRAINT ot_cancelada_por_check CHECK (((cancelada_por)::text = ANY ((ARRAY['CLIENTE'::character varying, 'TECNICO'::character varying, 'SISTEMA'::character varying, 'ADMINISTRADOR'::character varying])::text[]))),
    CONSTRAINT ot_categoria_servicio_check CHECK (((categoria_servicio)::text = ANY ((ARRAY['REFRIGERACION'::character varying, 'AIRE_ACONDICIONADO'::character varying, 'ELECTRICIDAD'::character varying, 'ELECTRODOMESTICOS'::character varying])::text[]))),
    CONSTRAINT ot_estado_check CHECK (((estado)::text = ANY ((ARRAY['SOLICITADA'::character varying, 'BUSCANDO_TECNICO'::character varying, 'ASIGNADA'::character varying, 'EN_CAMINO'::character varying, 'EN_DIAGNOSTICO'::character varying, 'EN_REPARACION'::character varying, 'FINALIZADA'::character varying, 'CANCELADA'::character varying, 'SIN_TECNICOS_DISPONIBLES'::character varying, 'DISPUTADA'::character varying])::text[]))),
    CONSTRAINT ot_motivo_cancelacion_check CHECK (((motivo_cancelacion)::text = ANY ((ARRAY['CANCELACION_CLIENTE'::character varying, 'CANCELACION_TECNICO'::character varying, 'RECHAZO_PRESUPUESTO'::character varying, 'RESOLUCION_DISPUTA_SIN_ACUERDO'::character varying])::text[])))
);

CREATE TABLE ot_estado_historial (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ot_id uuid NOT NULL,
    estado_origen character varying(30),
    estado_destino character varying(30) NOT NULL,
    actor_usuario_id bigint,
    actor_rol character varying(20),
    actor character varying(20),
    ocurrido_en timestamp(6) with time zone NOT NULL,
    motivo character varying(500),
    CONSTRAINT ot_estado_historial_actor_check CHECK (((actor)::text = ANY ((ARRAY['CLIENTE'::character varying, 'TECNICO'::character varying, 'SISTEMA'::character varying, 'ADMINISTRADOR'::character varying])::text[]))),
    CONSTRAINT ot_estado_historial_estado_destino_check CHECK (((estado_destino)::text = ANY ((ARRAY['SOLICITADA'::character varying, 'BUSCANDO_TECNICO'::character varying, 'ASIGNADA'::character varying, 'EN_CAMINO'::character varying, 'EN_DIAGNOSTICO'::character varying, 'EN_REPARACION'::character varying, 'FINALIZADA'::character varying, 'CANCELADA'::character varying, 'SIN_TECNICOS_DISPONIBLES'::character varying, 'DISPUTADA'::character varying])::text[]))),
    CONSTRAINT ot_estado_historial_estado_origen_check CHECK (((estado_origen)::text = ANY ((ARRAY['SOLICITADA'::character varying, 'BUSCANDO_TECNICO'::character varying, 'ASIGNADA'::character varying, 'EN_CAMINO'::character varying, 'EN_DIAGNOSTICO'::character varying, 'EN_REPARACION'::character varying, 'FINALIZADA'::character varying, 'CANCELADA'::character varying, 'SIN_TECNICOS_DISPONIBLES'::character varying, 'DISPUTADA'::character varying])::text[])))
);

CREATE TABLE oferta_ot (
    id uuid PRIMARY KEY,
    ot_id uuid NOT NULL,
    tecnico_id uuid NOT NULL,
    radio_km double precision,
    estado character varying(20) NOT NULL,
    creada_en timestamp(6) with time zone,
    expira_en timestamp(6) with time zone,
    resuelta_en timestamp(6) with time zone,
    CONSTRAINT oferta_ot_estado_check CHECK (((estado)::text = ANY ((ARRAY['PENDIENTE'::character varying, 'ACEPTADA'::character varying, 'EXPIRADA'::character varying, 'CANCELADA'::character varying])::text[])))
);

CREATE TABLE liquidacion (
    id uuid PRIMARY KEY,
    ot_id uuid NOT NULL,
    tecnico_id uuid NOT NULL,
    monto_cobrado numeric(12,2) NOT NULL,
    medio_pago character varying(20) NOT NULL,
    porcentaje_comision numeric(5,4) NOT NULL,
    valor_comision numeric(12,2) NOT NULL,
    estado character varying(30) NOT NULL,
    comprobante_url character varying(1000),
    motivo_rechazo character varying(500),
    creada_en timestamp(6) with time zone,
    verificada_en timestamp(6) with time zone,
    CONSTRAINT liquidacion_ot_id_key UNIQUE (ot_id),
    CONSTRAINT liquidacion_estado_check CHECK (((estado)::text = ANY ((ARRAY['PENDIENTE_CONSIGNACION'::character varying, 'EN_VERIFICACION'::character varying, 'APROBADA'::character varying, 'RECHAZADA'::character varying])::text[]))),
    CONSTRAINT liquidacion_medio_pago_check CHECK (((medio_pago)::text = ANY ((ARRAY['EFECTIVO'::character varying, 'TRANSFERENCIA'::character varying])::text[])))
);

CREATE TABLE disputa (
    id uuid PRIMARY KEY,
    ot_id uuid NOT NULL,
    motivo character varying(1000) NOT NULL,
    estado character varying(30) NOT NULL,
    resolucion character varying(1000),
    creada_en timestamp(6) with time zone,
    resuelta_en timestamp(6) with time zone,
    CONSTRAINT disputa_estado_check CHECK (((estado)::text = ANY ((ARRAY['ABIERTA'::character varying, 'RESUELTA_CON_ACUERDO'::character varying, 'RESUELTA_SIN_ACUERDO'::character varying])::text[])))
);

CREATE TABLE proveedor (
    id uuid PRIMARY KEY,
    usuario_id bigint NOT NULL,
    razon_social character varying(255) NOT NULL,
    nit character varying(50) NOT NULL,
    telefono character varying(30),
    direccion character varying(500),
    latitud double precision,
    longitud double precision,
    categorias_insumo character varying(1000),
    activo boolean NOT NULL,
    creado_en timestamp(6) with time zone,
    CONSTRAINT proveedor_usuario_id_key UNIQUE (usuario_id),
    CONSTRAINT proveedor_nit_key UNIQUE (nit)
);

CREATE TABLE requerimiento_insumo (
    id uuid PRIMARY KEY,
    ot_id uuid NOT NULL,
    tecnico_id uuid NOT NULL,
    estado character varying(20) NOT NULL,
    observaciones character varying(1000),
    creada_en timestamp(6) with time zone,
    expira_en timestamp(6) with time zone,
    resuelta_en timestamp(6) with time zone,
    version bigint NOT NULL,
    CONSTRAINT requerimiento_insumo_estado_check CHECK (((estado)::text = ANY ((ARRAY['SOLICITADO'::character varying, 'ASIGNADO'::character varying, 'ENTREGADO'::character varying, 'SIN_PROVEEDOR'::character varying])::text[])))
);

CREATE TABLE requerimiento_insumo_item (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    requerimiento_id uuid NOT NULL,
    descripcion character varying(500) NOT NULL,
    cantidad integer NOT NULL,
    CONSTRAINT fk_requerimiento_insumo_item_requerimiento_id
        FOREIGN KEY (requerimiento_id) REFERENCES requerimiento_insumo(id)
);

CREATE TABLE oferta_insumo (
    id uuid PRIMARY KEY,
    requerimiento_id uuid NOT NULL,
    proveedor_id uuid NOT NULL,
    estado character varying(20) NOT NULL,
    creada_en timestamp(6) with time zone,
    expira_en timestamp(6) with time zone,
    resuelta_en timestamp(6) with time zone,
    version bigint NOT NULL,
    CONSTRAINT oferta_insumo_estado_check CHECK (((estado)::text = ANY ((ARRAY['PENDIENTE'::character varying, 'ACEPTADA'::character varying, 'RECHAZADO'::character varying, 'EXPIRADA'::character varying, 'CANCELADA'::character varying])::text[])))
);

-- =============================================================================
-- Índices (mismos 17 declarados hoy en @Table(indexes=...) de las entidades)
-- =============================================================================

CREATE INDEX idx_ot_cliente_id ON ot (cliente_id);
CREATE INDEX idx_ot_tecnico_id ON ot (tecnico_id);
CREATE INDEX idx_ot_estado ON ot (estado);

CREATE INDEX idx_oferta_ot_ot_id ON oferta_ot (ot_id);
CREATE INDEX idx_oferta_ot_tecnico_id ON oferta_ot (tecnico_id);

CREATE INDEX idx_disputa_ot_id ON disputa (ot_id);
CREATE INDEX idx_disputa_estado ON disputa (estado);

CREATE INDEX idx_liquidacion_tecnico_id ON liquidacion (tecnico_id);
CREATE INDEX idx_liquidacion_estado ON liquidacion (estado);

CREATE INDEX idx_tecnico_estado_operativo ON tecnico (estado_operativo);

CREATE INDEX idx_documento_tecnico_tecnico_id ON documento_tecnico (tecnico_id);

CREATE INDEX idx_token_recuperacion_usuario_id ON token_recuperacion (usuario_id);

CREATE INDEX idx_ot_estado_historial_ot_id ON ot_estado_historial (ot_id);

CREATE INDEX idx_req_insumo_ot_id ON requerimiento_insumo (ot_id);
CREATE INDEX idx_req_insumo_estado ON requerimiento_insumo (estado);

CREATE INDEX idx_oferta_insumo_req_id ON oferta_insumo (requerimiento_id);
CREATE INDEX idx_oferta_insumo_proveedor_id ON oferta_insumo (proveedor_id);

-- Índice GiST parcial para la búsqueda espacial (RNF-03): solo sobre
-- técnicos activos, aprobados y disponibles — el mismo predicado que
-- siempre aplica PostgisTecnicoDisponibilidadAdapter.
CREATE INDEX idx_tecnico_disponible_ubicacion_geo
    ON tecnico USING GIST ((ST_MakePoint(longitud, latitud)::geography))
    WHERE activo = true AND estado_validacion = 'APROBADO' AND estado_operativo = 'DISPONIBLE';
