-- Tabla documento_proveedor, espejo exacto de documento_tecnico (V1 linea 57)
-- con proveedor_id en lugar de tecnico_id.
--
-- Por que existe esta migracion: la entidad DocumentoProveedorJpaEntity llego
-- al repositorio antes que su tabla. La tabla documento_proveedor solo existia
-- como DDL aplicado a mano en la base local de desarrollo y nunca quedo
-- capturada en una migracion de Flyway. Como la app corre con
-- SPRING_JPA_HIBERNATE_DDL_AUTO=validate (docker-compose.yml), Hibernate exige
-- que la exista fisicamente, y el reseteo reciente de la base borro ese DDL
-- manual, dejando al descubierto el hueco: la entidad sin tabla y sin
-- migracion que la crees.
--
-- Esto es exactamente por que el DDL manual es un bug y no una comodidad: el
-- DDL a mano no entra en flyway_schema_history, asi que no tiene checksum ni
-- version. Flyway no lo conoce, no lo re-corre y no lo puede reponer. Un
-- CREATE TABLE escrito a mano sobrevive hasta el proximo reset y despues
-- desaparece sin dejar rastro.
--
-- V1__baseline_esquema_actual.sql es snapshot y usa
-- spring.flyway.baseline-on-migrate con baseline-version=1, asi que NO se
-- re-corre en bases ya baselined. Toda tabla nueva va aqui.
--
-- Sentencias planas (sin IF NOT EXISTS), igual que V2/V3/V4: Flyway versiona
-- por checksum y nunca re-corre una migracion aplicada.
--
-- Sin ON DELETE CASCADE, siguiendo el precedente de V2: ninguna FK del
-- esquema declara cascade (fk_documento_tecnico_tecnico_id included). El
-- borrado de un proveedor con documentos se resuelve en el dominio, no en la
-- base; inventar cascade aqui daria a esta tabla un comportamiento de borrado
-- distinto al de su gemela y dejaria la integridad entre modulos en un estado
-- que ningun otro modulo tiene.
--
-- NOT VALID en la FK, como todas las de V2: la constraint queda activa para
-- todo INSERT/UPDATE futuro desde el deploy, pero Postgres no escanea filas
-- existentes. En una tabla recien creada la tabla esta vacia, asi que el
-- NOT VALID es puro rigor de estilo consistente; validarla despues es un
-- ALTER TABLE documento_proveedor VALIDATE CONSTRAINT
-- fk_documento_proveedor_proveedor_id, deliberadamente fuera de Flyway.

CREATE TABLE documento_proveedor (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    proveedor_id uuid NOT NULL,
    tipo character varying(255) NOT NULL,
    fecha_vencimiento date
);

CREATE INDEX idx_documento_proveedor_proveedor_id ON documento_proveedor (proveedor_id);

ALTER TABLE documento_proveedor ADD CONSTRAINT fk_documento_proveedor_proveedor_id
    FOREIGN KEY (proveedor_id) REFERENCES proveedor(id) NOT VALID;